# Based on official Elasticsearch image
FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.3

# Install nori (Korean morphological analyzer) plugin
RUN bin/elasticsearch-plugin install analysis-nori
