spring:
  application:
    name: open-context-core
  
  # Database Configuration (Docker)
  datasource:
    url: jdbc:postgresql://postgres:5432/opencontext
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Flyway Configuration (Docker)
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

  # Servlet Configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Application-specific Configuration (Docker)
app:
  # Elasticsearch Configuration (Docker)
  elasticsearch:
    url: http://elasticsearch:9200
    index: document_chunks_index
  
  # Ollama Configuration (Docker)
  ollama:
    api:
      url: http://ollama:11434
    embedding:
      model: dengcao/Qwen3-Embedding-0.6B:F16
  
  # Embedding Configuration
  embedding:
    batch-size: 10
  
  # Search Configuration
  search:
    snippet-max-length: 50
    bm25-weight: 0.3
    vector-weight: 0.7
  
  # Content Configuration
  content:
    default-max-tokens: 25000
    tokenizer: tiktoken-cl100k_base
  
  # Unstructured API Configuration
  unstructured:
    api:
      url: http://unstructured-api:8000

# MinIO Configuration (Docker)
minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123!
  bucket-name: opencontext-documents



# Application Configuration
opencontext:
  api:
    key: dev-api-key-123
  processing:
    chunk-size: 1000
    chunk-overlap: 200

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.opencontext: DEBUG
    org.springframework.data.elasticsearch: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
