spring:
  application:
    name: open-context-core
  
  profiles:
    active: dev
  
  # Database Configuration (Development)
  datasource:
    url: jdbc:postgresql://localhost:5432/opencontext
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Flyway Configuration
  flyway:
    baseline-on-migrate: true

  # Servlet Configuration
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# Application-specific Configuration
app:
  # Elasticsearch Configuration
  elasticsearch:
    url: http://localhost:9200
    index: document_chunks_index
  
  # Ollama Configuration  
  ollama:
    api:
      url: http://localhost:11434
    embedding:
      model: dengcao/Qwen3-Embedding-0.6B:F16
  
  # Embedding Configuration
  embedding:
    batch-size: 10
  
  # Search Configuration
  search:
    snippet-max-length: 50
    bm25-weight: 0.3
    vector-weight: 0.7

# MinIO Configuration (Development)
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123!
  bucket-name: opencontext-documents

# Unstructured.io Configuration (Development)
unstructured:
  base-url: http://localhost:8000

# Application Configuration
opencontext:
  api:
    key: dev-api-key-123
  processing:
    chunk-size: 1000
    chunk-overlap: 200

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.opencontext: DEBUG
    org.springframework.data.elasticsearch: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
